version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8008:8000"
    networks:
      - laravel-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:8.0
    container_name: be-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis
    container_name: be-redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    networks:
      - laravel-network
    volumes:
      - redis_data:/var/lib/redis


  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8009:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
